In [274]:
import spacy
import numpy as np
import pandas as pd

In [275]:
df=pd.read_csv(r"Symptom2Disease.csv")
df.head()

Unnamed: 0      label                                               text
0           0  Psoriasis  I have been experiencing a skin rash on my arm...
1           1  Psoriasis  My skin has been peeling, especially on my kne...
2           2  Psoriasis  I have been experiencing joint pain in my fing...
3           3  Psoriasis  There is a silver like dusting on my skin, esp...
4           4  Psoriasis  My nails have small dents or pits in them, and...

In [276]:
df.columns

Index(['Unnamed: 0', 'label', 'text'], dtype='object')

In [277]:
df.drop('Unnamed: 0',axis=1,inplace=True)
df.head()

label                                               text
0  Psoriasis  I have been experiencing a skin rash on my arm...
1  Psoriasis  My skin has been peeling, especially on my kne...
2  Psoriasis  I have been experiencing joint pain in my fing...
3  Psoriasis  There is a silver like dusting on my skin, esp...
4  Psoriasis  My nails have small dents or pits in them, and...

In [278]:
my_disease=df['label'].unique()
my_disease

array(['Psoriasis', 'Varicose Veins', 'Typhoid', 'Chicken pox',
       'Impetigo', 'Dengue', 'Fungal infection', 'Common Cold',
       'Pneumonia', 'Dimorphic Hemorrhoids', 'Arthritis', 'Acne',
       'Bronchial Asthma', 'Hypertension', 'Migraine',
       'Cervical spondylosis', 'Jaundice', 'Malaria',
       'urinary tract infection', 'allergy',
       'gastroesophageal reflux disease', 'drug reaction',
       'peptic ulcer disease', 'diabetes'], dtype=object)

In [279]:
my_dict={'Psoriasis':1, 'Varicose Veins':2, 'Typhoid':3, 'Chicken pox':4,
       'Impetigo':5, 'Dengue':6, 'Fungal infection':7, 'Common Cold':8,
       'Pneumonia':9, 'Dimorphic Hemorrhoids':10, 'Arthritis':11, 'Acne':12,
       'Bronchial Asthma':13, 'Hypertension':14, 'Migraine':15,
       'Cervical spondylosis':16, 'Jaundice':17, 'Malaria':18,
       'urinary tract infection':18, 'allergy':19,
       'gastroesophageal reflux disease':20, 'drug reaction':21,
       'peptic ulcer disease':22, 'diabetes':23}

In [280]:
len(my_disease)

24

In [281]:
nlp=spacy.load("en_core_web_lg")
doc=nlp("Bernie Sanders has taken America and the world")
doc.vector.shape

(300,)

In [282]:
df['text vector']=df['text'].apply(lambda x: nlp(x).vector)
df.head()

label                                               text  \
0  Psoriasis  I have been experiencing a skin rash on my arm...   
1  Psoriasis  My skin has been peeling, especially on my kne...   
2  Psoriasis  I have been experiencing joint pain in my fing...   
3  Psoriasis  There is a silver like dusting on my skin, esp...   
4  Psoriasis  My nails have small dents or pits in them, and...   

                                         text vector  
0  [-0.9800024, 0.23233683, -2.8956056, 0.4936634...  
1  [-0.6406128, -0.052214265, -3.7610066, -0.3640...  
2  [0.18709338, 0.41869602, -2.847488, -0.5365884...  
3  [-1.1879317, 0.48687568, -3.3808053, 0.4752692...  
4  [-0.74316317, 0.96162474, -4.350618, -0.047534...

In [283]:
df['label_num']=df['label'].apply(lambda x: my_dict[x])

In [284]:
df.head()

label                                               text  \
0  Psoriasis  I have been experiencing a skin rash on my arm...   
1  Psoriasis  My skin has been peeling, especially on my kne...   
2  Psoriasis  I have been experiencing joint pain in my fing...   
3  Psoriasis  There is a silver like dusting on my skin, esp...   
4  Psoriasis  My nails have small dents or pits in them, and...   

                                         text vector  label_num  
0  [-0.9800024, 0.23233683, -2.8956056, 0.4936634...          1  
1  [-0.6406128, -0.052214265, -3.7610066, -0.3640...          1  
2  [0.18709338, 0.41869602, -2.847488, -0.5365884...          1  
3  [-1.1879317, 0.48687568, -3.3808053, 0.4752692...          1  
4  [-0.74316317, 0.96162474, -4.350618, -0.047534...          1

In [285]:
df = df.sample(frac = 1)
df.head()

label  \
485             Dimorphic Hemorrhoids   
776              Cervical spondylosis   
1161                         diabetes   
1047  gastroesophageal reflux disease   
931           urinary tract infection   

                                                   text  \
485   I've been experiencing a lot of problems with ...   
776   My arms and legs have been weak, and I have be...   
1161  My vision is foggy, and it seems to be growing...   
1047  My throat often feels like it's on fire, espec...   
931   My pee smells strongly and is cloudy in appear...   

                                            text vector  label_num  
485   [0.6201701, 1.6383687, -3.2903316, -1.6322908,...         10  
776   [-0.9344119, -0.14979437, -3.2774932, -0.35201...         16  
1161  [-0.5241863, 0.44245565, -2.9382946, -1.004569...         23  
1047  [0.30641073, 0.3235194, -2.5786948, -1.1797795...         20  
931   [-0.8394503, 0.7801217, -3.101169, -0.45186615...         18

In [286]:
from sklearn.model_selection import train_test_split

X=df['text vector'].values
y=df['label']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42,shuffle=True)


In [287]:
y_train

543                Arthritis
1133    peptic ulcer disease
950                  allergy
411                Pneumonia
1                  Psoriasis
                ...         
509                Arthritis
320         Fungal infection
1182                diabetes
784     Cervical spondylosis
417                Pneumonia
Name: label, Length: 960, dtype: object

In [288]:
X_train[0]

array([ 2.93719590e-01,  2.21120238e+00, -4.13426828e+00, -6.01909161e-01,
        3.26805782e+00,  5.53525627e-01, -1.03297681e-01,  5.12723255e+00,
       -6.25758708e-01,  1.27364016e+00,  5.15338182e+00,  2.00599933e+00,
       -2.61881375e+00,  8.48389804e-01,  2.24022365e+00, -1.23533472e-01,
        9.40877676e-01, -2.43544602e+00, -1.30725098e+00, -2.41795278e+00,
        9.74185705e-01, -4.82368082e-01,  5.41910350e-01, -3.91757846e+00,
        3.41799974e-01, -3.24368811e+00, -2.95252776e+00, -1.36701536e+00,
       -9.68612492e-01,  1.33026624e+00,  1.12210107e+00, -6.77647665e-02,
       -1.03084850e+00, -1.34764647e+00, -2.13028717e+00, -7.60917425e-01,
       -1.14058697e+00,  2.64395905e+00,  2.28561115e+00,  1.59579480e+00,
        1.52828753e+00,  7.17738867e-01, -5.31332076e-01, -1.90705299e+00,
       -6.35066628e-01,  7.04948843e-01,  1.28584373e+00, -3.16152024e+00,
       -2.02578497e+00,  3.19605732e+00,  1.09804285e+00,  7.76921213e-01,
       -2.05838382e-01, -

In [289]:
# converting X_train to a 2D numpy array
X_train_2d=np.stack(X_train)
X_test_2d=np.stack(X_test)


In [290]:
X_train_2d

array([[ 2.9371959e-01,  2.2112024e+00, -4.1342683e+00, ...,
         3.1307441e-01, -4.5727015e+00,  1.3681923e+00],
       [-1.8071531e+00, -1.9360095e-02, -3.4666755e+00, ...,
         2.6570573e-01, -4.0285587e+00,  9.1242158e-01],
       [-1.1170607e-01, -3.1377935e-01, -2.2711110e+00, ...,
        -4.6166551e-01, -4.4491239e+00,  1.2306770e+00],
       ...,
       [-8.5572600e-01, -5.4070020e-01, -3.4198666e+00, ...,
         9.6730995e-01, -4.5316405e+00,  1.2322716e+00],
       [-1.1373304e+00,  1.2148006e-03, -3.2634153e+00, ...,
        -1.5138375e+00, -3.8735425e+00,  2.6321974e-01],
       [ 8.5780919e-02,  2.2255908e-01, -3.6410701e+00, ...,
         1.2926139e+00, -5.1379280e+00,  1.0771266e+00]], dtype=float32)

In [291]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.preprocessing import MinMaxScaler

scaler=MinMaxScaler()

scaled_train_embed=scaler.fit_transform(X_train_2d)
scaled_test_embed=scaler.transform(X_test_2d)


clf=MultinomialNB()
clf.fit(scaled_train_embed,y_train)

MultinomialNB()

In [292]:
len(scaled_train_embed[0])

300

In [293]:
scaled_test_embed

array([[0.21945351, 0.34431323, 0.3741032 , ..., 0.3683661 , 0.5688021 ,
        0.28735963],
       [0.32940313, 0.4946605 , 0.5334776 , ..., 0.63255525, 0.6749734 ,
        0.7248497 ],
       [0.53760785, 0.4966918 , 0.54651755, ..., 0.5769987 , 0.57277244,
        0.42831784],
       ...,
       [0.73873764, 0.64301836, 0.2887516 , ..., 0.5727656 , 0.3845992 ,
        0.42999288],
       [0.13233495, 0.193349  , 0.8250196 , ..., 0.3416348 , 0.6870241 ,
        0.50736904],
       [0.5710933 , 0.13076304, 0.50966597, ..., 0.4065566 , 0.5449169 ,
        0.22445063]], dtype=float32)

In [294]:
pred=clf.predict(scaled_test_embed)

In [295]:
pred

array(['Fungal infection', 'Hypertension', 'Chicken pox', 'Chicken pox',
       'Impetigo', 'Pneumonia', 'peptic ulcer disease', 'Psoriasis',
       'Jaundice', 'gastroesophageal reflux disease', 'Hypertension',
       'Impetigo', 'Fungal infection', 'gastroesophageal reflux disease',
       'Arthritis', 'Arthritis', 'Fungal infection', 'diabetes',
       'diabetes', 'Acne', 'Chicken pox', 'Psoriasis', 'Impetigo',
       'Pneumonia', 'Jaundice', 'Malaria', 'Dimorphic Hemorrhoids',
       'Common Cold', 'Jaundice', 'Hypertension', 'Migraine', 'Pneumonia',
       'Typhoid', 'Varicose Veins', 'Dimorphic Hemorrhoids',
       'Chicken pox', 'Common Cold', 'diabetes', 'Pneumonia', 'Impetigo',
       'Acne', 'Impetigo', 'Chicken pox', 'Acne', 'Jaundice',
       'gastroesophageal reflux disease', 'Impetigo', 'Acne',
       'Bronchial Asthma', 'Fungal infection', 'Hypertension',
       'Psoriasis', 'Common Cold', 'Typhoid', 'Bronchial Asthma',
       'Psoriasis', 'gastroesophageal reflux diseas

In [296]:
from sklearn.metrics import classification_report

In [297]:
print(classification_report(y_test,pred))

                                 precision    recall  f1-score   support

                           Acne       0.87      0.93      0.90        14
                      Arthritis       0.89      0.89      0.89         9
               Bronchial Asthma       0.62      0.71      0.67         7
           Cervical spondylosis       0.73      0.73      0.73        11
                    Chicken pox       0.50      0.75      0.60        12
                    Common Cold       0.70      0.88      0.78         8
                         Dengue       0.50      0.12      0.20         8
          Dimorphic Hemorrhoids       0.75      1.00      0.86         9
               Fungal infection       0.90      0.69      0.78        13
                   Hypertension       0.62      0.50      0.55        16
                       Impetigo       0.54      0.70      0.61        10
                       Jaundice       0.87      1.00      0.93        13
                        Malaria       0.62      1.

Using KNN model


In [298]:
# from sklearn.neighbors import KNeighborsClassifier

# clf=KNeighborsClassifier(n_neighbors=5, metric='euclidean')

# clf.fit(X_train_2d,y_train)

# y_pred=clf.predict(X_test_2d)

# print(classification_report(y_test,pred))

In [299]:
# y_pred

In [300]:
# y_test

In [301]:
type(X_train)

numpy.ndarray

In [302]:
my_symptoms="I have been experiencing a skin rash on my arms, legs, and torso for the past few weeks. It is red, itchy, and covered in dry, scaly patches."
my_vector=nlp(my_symptoms).vector
# my_vector

In [303]:
# final_pred_stack=np.stack(my_vector)
# final_pred_stack
# scaled_train_final=scaler.transform(my_vector)
final_pred=clf.predict([my_vector])
print(final_pred)

['Fungal infection']


In [304]:
# print(my_disease[final_pred-1])